_BASE_: "../Base_det.yaml"

MODEL:
  #WEIGHTS: "output/R50/150k_tt_mlt_13_15_textocr/pretrain/model_final.pth"
  WEIGHTS: "/home/isi_cvpr/Documents/Shashwat/weights/enhanced/ic15/model_final.pth"
  TRANSFORMER:
    INFERENCE_TH_TEST: 0.3

DATASETS:
  TRAIN: ("ic15_train",)
  TEST: ("ic15_test",)

INPUT:
  MIN_SIZE_TRAIN: (800,900,1000,1100,1200,1300,1400)
  MAX_SIZE_TRAIN: 3000
  MIN_SIZE_TEST: 1440
  MAX_SIZE_TEST: 4000
  CROP:
    ENABLED: False
  ROTATE: True

SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 1e-5
  LR_BACKBONE: 1e-6
  WARMUP_ITERS: 0
  STEPS: (500,)  # no step
  MAX_ITER: 1000
  CHECKPOINT_PERIOD: 500

TEST:
  EVAL_PERIOD: 500
  # 1 - Generic, 2 - Weak, 3 - Strong (for icdar2015)
  LEXICON_TYPE: 1
 

OUTPUT_DIR: "output/R50/150k_tt_mlt_13_15_textocr/finetune/ic15"
