_BASE_: "../Base_det.yaml"

MODEL:
  WEIGHTS: "output/R50/150k_tt_mlt_13_15_textocr/pretrain/model_final.pth"

DATASETS:
  TRAIN: ("totaltext_train",)
  TEST: ("ctw1500_test",)

SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 1e-5
  LR_BACKBONE: 1e-6
  WARMUP_ITERS: 0
  STEPS: (2000,)  # no step
  MAX_ITER: 6000
  CHECKPOINT_PERIOD: 1000

TEST:
  EVAL_PERIOD: 500

OUTPUT_DIR: "output/R50/150k_tt_mlt_13_15_textocr/finetune/totaltext"
