_BASE_: "../Base_det.yaml"

MODEL:
  WEIGHTS: "" #initialize weight

DATASETS:
  TRAIN: ("totaltext_train",)
  TEST: ("totaltext_test",)

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 1e-5
  LR_BACKBONE: 1e-6
  WARMUP_ITERS: 0
  STEPS: (8000,)  # no step
  MAX_ITER: 12000
  CHECKPOINT_PERIOD: 2000

TEST:
  EVAL_PERIOD: 1000

OUTPUT_DIR: "output/R50/150k_tt_mlt_13_15/finetune/totaltext"