_BASE_: "../Base_det.yaml"

MODEL:
  WEIGHTS: "" #initialize weight
  TRANSFORMER: 
    INFERENCE_TH_TEST: 0.3 #
    VOC_SIZE: 96
    NUM_POINTS: 50
    LOSS:
        BEZIER_SAMPLE_POINTS: 50
        BEZIER_CLASS_WEIGHT: 1.0
        BEZIER_COORD_WEIGHT: 0.5
        POINT_CLASS_WEIGHT: 1.0
        POINT_COORD_WEIGHT: 0.5
        POINT_TEXT_WEIGHT: 1.0 #0.5
        BOUNDARY_WEIGHT: 0.25
  
DATASETS:
  TRAIN: ("underwater_train",)
  TEST: ("underwater_test",)

INPUT:
  ROTATE: False
  MIN_SIZE_TEST: 1000
  MAX_SIZE_TEST: 1200
  CROP:
    ENABLED: False
  ROTATE: False

SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 5e-5
  LR_BACKBONE: 5e-6
  WARMUP_ITERS: 0
  STEPS: (8000,)
  MAX_ITER: 12000
  CHECKPOINT_PERIOD: 4000

TEST:
  EVAL_PERIOD: 400

OUTPUT_DIR: "output/R50/underwater/finetune_maxlen50_96voc"
